In [16]:
import pandas as pd

In [17]:
df_peliculas= pd.read_csv('..\Proyecto individual Henry\Data\collection.csv')

In [33]:
df_peliculas2=pd.read_csv('..\Proyecto individual Henry\Data\peliculas.csv')

In [36]:
df_peliculas2

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,release_year,return
0,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"['Animation', 'Comedy', 'Family']",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,['Pixar Animation Studios'],['United States of America'],1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,7.7,5415.0,1995,12.451801
1,NaN,65000000,"['Adventure', 'Fantasy', 'Family']",8844,en,When siblings Judy and Peter discover an encha...,17.015539,"['TriStar Pictures', 'Teitler Film', 'Intersco...",['United States of America'],1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0,1995,4.043035
2,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"['Romance', 'Comedy']",15602,en,A family wedding reignites the ancient feud be...,11.712900,"['Warner Bros.', 'Lancaster Gate']",['United States of America'],1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0,1995,0.000000
3,NaN,16000000,"['Comedy', 'Drama', 'Romance']",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,['Twentieth Century Fox Film Corporation'],['United States of America'],1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0,1995,5.090760
4,"{'id': 96871, 'name': 'Father of the Bride Col...",0,['Comedy'],11862,en,Just when George Banks has recovered from his ...,8.387519,"['Sandollar Productions', 'Touchstone Pictures']",['United States of America'],1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0,1995,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45341,NaN,0,"['Drama', 'Action', 'Romance']",30840,en,"Yet another version of the classic epic, with ...",5.683753,"['Westdeutscher Rundfunk (WDR)', 'Working Titl...","['Canada', 'Germany', 'United Kingdom', 'Unite...",1991-05-13,0.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Robin Hood,5.7,26.0,1991,0.000000
45342,NaN,0,['Drama'],111109,tl,An artist struggles to finish his work while a...,0.178241,['Sine Olivia'],['Philippines'],2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,9.0,3.0,2011,0.000000
45343,NaN,0,"['Action', 'Drama', 'Thriller']",67758,en,"When one of her hits goes wrong, a professiona...",0.903007,['American World Pictures'],['United States of America'],2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,3.8,6.0,2003,0.000000
45344,NaN,0,[],227506,en,"In a small town live two brothers, one a minis...",0.003503,['Yermoliev'],['Russia'],1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,0.0,0.0,1917,0.000000
45345,NaN,0,[],461257,en,50 years after decriminalisation of homosexual...,0.163015,[],['United Kingdom'],2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,0.0,0.0,2017,0.000000

In [34]:
df_peliculas

0                 Toy Story Collection
1            Grumpy Old Men Collection
2       Father of the Bride Collection
3                James Bond Collection
4                     Balto Collection
                     ...
4480           The Carry On Collection
4481           The Carry On Collection
4482           The Carry On Collection
4483    DC Super Hero Girls Collection
4484              Red Lotus Collection
Name: name, Length: 4485, dtype: object

In [19]:
df_peliculas['name']=df_peliculas['name'].str.replace("'","")

In [20]:
df_peliculas = df_peliculas['name'].copy()

In [38]:
df_peliculas2= df_peliculas2['revenue'].copy()

In [22]:
df_peliculas_franquias = df_peliculas.value_counts().reset_index()
df_peliculas_franquias.columns = ['franquicia', 'cantidad']

In [23]:
df_peliculas_franquias

                       franquicia  cantidad
0                 The Bowery Boys        29
1                 Totò Collection        27
2           James Bond Collection        26
3     ZatôichiThe Blind Swordsman        26
4         The Carry On Collection        25
...                           ...       ...
1690       Glass Tiger collection         1
1691  Kathleen Madigan Collection         1
1692           The Big Bottom Box         1
1693             Joséphine - Saga         1
1694         Red Lotus Collection         1

[1695 rows x 2 columns]